Update ReviewVirtualSwapSettlement
saddle-finance/saddle-frontend pull request #970
Opened 2022-04-13 22:52 UTC by nkrulikovsky

## What does this PR do?

- Remove old `Button` and its `scss` completely
- Update `ReviewVirutalSwapSettlement`
- Remove `ReviewSwap.scss`

## Context

https://www.figma.com/file/Aa3IfDUO68aCNr8nZTuQ8S/Product-Design-with-MUI?node-id=257%3A31934

## Screenshot
![Screen Shot 2022-04-14 at 1 51 20 AM](https://user-images.githubusercontent.com/75422800/163282644-67e9a835-8340-44d2-9f76-6a8b85532a9e.png)
![Screen Shot 2022-04-14 at 1 51 35 AM](https://user-images.githubusercontent.com/75422800/163282667-02e6a101-be5e-4aae-8735-b2777a64969f.png)
![Screen Shot 2022-04-14 at 1 51 52 AM](https://user-images.githubusercontent.com/75422800/163282695-10359db5-5a1a-4d95-a94d-a4b91c588aae.png)
![Screen Shot 2022-04-14 at 1 52 04 AM](https://user-images.githubusercontent.com/75422800/163282712-9c3603f7-b845-4568-9dd0-2b7e8c6d190b.png)

2022-04-15 16:47 UTC, ug02fast commented
Is it possible to align this arrow in the middle between the icons? 
<img width="106" alt="image" src="https://user-images.githubusercontent.com/5507707/163597868-cacfd03c-ce48-4a27-acb2-0a2b53f2a60d.png">

2022-04-16 16:32 UTC, nkrulikovsky commented
@ug02fast 

Thank you for reviewing this PR.
I aligned tokenIcon and arrow icon by giving them same size.

2022-04-16 16:41 UTC, ug02fast requested changes
looks good just small suggestion

2022-04-16 16:41 UTC, ug02fast commented on public/locales/en.json
> +  "step2Withdraw": "Step 2: Review Withdraw",
```suggestion
  "step2ReviewWithdraw": "Step 2: Review Withdraw",
```

2022-04-16 16:41 UTC, ug02fast commented on src/components/ReviewVirtualSwapSettlement.tsx
> +        {isWithdrawAction ? t("step2Withdraw") : t("step2ReviewSettle")}
```suggestion
        {isWithdrawAction ? t("step2ReviewWithdraw") : t("step2ReviewSettle")}
```

2022-04-19 11:00 UTC, nkrulikovsky commented on public/locales/en.json
> +  "step2Withdraw": "Step 2: Review Withdraw",
Updated!

2022-04-19 11:00 UTC, nkrulikovsky commented on src/components/ReviewVirtualSwapSettlement.tsx
> +        {isWithdrawAction ? t("step2Withdraw") : t("step2ReviewSettle")}
Done!

2022-04-19 14:53 UTC, ug02fast approved these changes

2022-04-19 20:24 UTC, merged